### PR TITLE
commit Test2 class to branchX

### PR DESCRIPTION
**Pull request by anushapachi**
Hi , 

I have committed Test2. Please review and approve.

Regards
Anusha Pachi

### CODE REVIEW

**Comment by anushapachi** [comment]
Hi anushapachi,

Your code looks good, please add one more check.

**Comment by Pradhakrishna284** [comment]
Hi AnushaPachi, 

Your code looks good, please have a look once.

**Comment by anushapachi** [comment]
Hi Pradhakrishna284, 

I have added additional checks. Please review

**Comment by Pradhakrishna284** [comment]
Hi anushapachi, 
your code looks good, please go ahead and merge to master branch.
Regards
Pradhakrishna284

**Pull request merged**
